name: Trigger auto deployment for order-processor-http

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ debugging-demo ]
    paths:
    - 'PizzaOrderProcessor1/**'
    - '.github/workflows/order-processor-http-AutoDeployTrigger-d2cce1ba-94b0-4152-af73-267c09c3f22e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.ORDERPROCESSORHTTP_REGISTRY_USERNAME }}
          password: ${{ secrets.ORDERPROCESSORHTTP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: poppastring/order-processor-http:${{ github.sha }}
          file: ./PizzaOrderProcessor1/Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ORDERPROCESSORHTTP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n order-processor-http -g PizzaOrderDemo5 --server docker.io --username  ${{ secrets.ORDERPROCESSORHTTP_REGISTRY_USERNAME }} --password ${{ secrets.ORDERPROCESSORHTTP_REGISTRY_PASSWORD }}
            az containerapp update -n order-processor-http -g PizzaOrderDemo5 --image poppastring/order-processor-http:${{ github.sha }}
